CENTIMETER = 2.54
INCH_CALCULATION = 1 * CENTIMETER

START_INCH = 1
START_CENTIMETER = 100

print(f"Inches      Centimeters  | Centimeters    Inches")
while START_INCH <= 19 and START_CENTIMETER >= 55:
    print(f"{START_INCH}   {START_INCH * INCH_CALCULATION}  | {START_CENTIMETER}       {START_CENTIMETER / CENTIMETER}")
    START_INCH += 2
    START_CENTIMETER -= 5
